upstream backend_upstream {
    server backend:8081;
}

server {
    listen 80;
    index index.html;
    server_tokens off;
    
    server_name _;
    root /usr/share/nginx/html;

    location = / {
        return 302 /momo-store/;
    }

    location ^~ /momo-store/products {
        proxy_pass http://backend_upstream/products;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ^~ /momo-store/categories {
        proxy_pass http://backend_upstream/categories;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ^~ /momo-store/orders {
        proxy_pass http://backend_upstream/orders;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ^~ /momo-store/auth/whoami {
        proxy_pass http://backend_upstream/auth/whoami;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /momo-store/ {
        root /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /momo-store/index.html; 
    }
}